### ISSUE TITLE
Mehrzeilige Gleichungen

### ISSUE THREAD

**Issue by albedoklaus** [albedoklaus/ptp4ss2020#1]
```latex
\section{Eigenschaften der Wellenfunktion}

\subsection{}
\begin{align}
\begin{split}
	\Braket{\phi | \psi} &= \int_{\mathbb{R}^d}\phi(t,\vec{r})^*\psi(t,\vec{r})\text{d}^d\vec{r} \\
	                     &= \int_{\mathbb{R}^d}((\phi(t,\vec{r})^*(\psi(t,\vec{r}))^*)^*\text{d}^d\vec{r} \\
	                     &= \int_{\mathbb{R}^d}(\phi(t,\vec{r}\psi(t,\vec{r})^*)^*\text{d}^d\vec{r} \\
	                     &= (\int_{\mathbb{R}^d}\phi(t,\vec{r}\psi(t,\vec{r})^*\text{d}^d\vec{r})^* \\
	                     &= \Braket{\psi|\phi}^*
\end{split}
\end{align}

```
![screenshot](https://user-images.githubusercontent.com/49734806/80891650-f0ca1980-8cb4-11ea-9025-233136f862fd.png)

**Comment by albedoklaus** [comment]
@TheProfms Ist das eher was du meinst?

**Comment by TheProfms** [comment]
@albedoklaus Perfekt

**Comment by albedoklaus** [comment]
Ich nehm mal an, das war nur eine generelle TeX Frage und wird dann erst auf dem nächsten Blatt angewendet, oder?

**Comment by albedoklaus** [comment]
Das mit `\left(` und `\right)` kennst du auch, oder?

**Comment by TheProfms** [comment]
> Ich nehm mal an, das war nur eine generelle TeX Frage und wird dann erst auf dem nächsten Blatt angewendet, oder?

Du hast es bei dem hier ja schon angewendet, hab mir schon Sorgen wegen Inkonsistenz gemacht. Aber ja, kommt beim nächsten zur Anwendung, eine Lernkurve zu zeigen ist ja natürlich

**Comment by TheProfms** [comment]
> Das mit \left( und \right) kennst du auch, oder?

Hab es mal gesehen, mehr aber auch nicht

**Comment by albedoklaus** [comment]
> Hab es mal gesehen, mehr aber auch nicht

Siehe die vierte Zeile oben im Screenshot. Da ist die Klammer ja zu klein für das Integralzeichen. Mit `\left` und `\right` vor/nach `()` oder `[]` etc. kann man das anpassen.
