### ISSUE TITLE
Zettel 3 i zu viel?

### ISSUE THREAD

**Issue by albedoklaus** [albedoklaus/ptp4ss2020#3]
https://github.com/albedoklaus/ptp4ss2020/blob/0cf960590ee6a5d2bf83b538fdd2333f28535a60/Zettel3.tex#L168-L170

Muss da links das i nicht noch hin und kürzt sich dann weg?

**Comment by TheProfms** [comment]
Hast Recht. Komplexe Frequenz macht in dem Zusammenhang wenig Sinn.
